<a href="https://colab.research.google.com/github/harshs-data/Pytorch/blob/main/pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [6]:
df.shape

(569, 33)

In [7]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)
df

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [8]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.20, random_state=42)

In [9]:
X_train.shape

(455, 30)

In [10]:
y_train.shape

(455,)

In [11]:
# Scaling

scaler = StandardScaler()
X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

In [12]:
X_train_scale

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [13]:
X_test_scale

array([[-0.46649743, -0.13728933, -0.44421138, ..., -0.19435087,
         0.17275669,  0.20372995],
       [ 1.36536344,  0.49866473,  1.30551088, ...,  0.99177862,
        -0.561211  , -1.00838949],
       [ 0.38006578,  0.06921974,  0.40410139, ...,  0.57035018,
        -0.10783139, -0.20629287],
       ...,
       [-0.73547237, -0.99852603, -0.74138839, ..., -0.27741059,
        -0.3820785 , -0.32408328],
       [ 0.02898271,  2.0334026 ,  0.0274851 , ..., -0.49027026,
        -1.60905688, -0.33137507],
       [ 1.87216885,  2.80077153,  1.80354992, ...,  0.7925579 ,
        -0.05868885, -0.09467243]])

In [14]:
# label encoding

le = LabelEncoder()
y_train_le = le.fit_transform(y_train)
y_test_le = le.transform(y_test)

In [15]:
y_train_le

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0])

In [16]:
X_train_tensor = torch.from_numpy(X_train_scale)
X_test_tensor = torch.from_numpy(X_test_scale)
y_train_tensor = torch.from_numpy(y_train_le)
y_test_tensor = torch.from_numpy(y_test_le)

In [17]:
X_train_tensor.shape

torch.Size([455, 30])

In [18]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

In [24]:
# important parameters

learning_rate = 0.1
epochs = 100

### Training pipeline

In [25]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.7336246787976797
Epoch: 2, Loss: 3.606854423347359
Epoch: 3, Loss: 3.475223192952168
Epoch: 4, Loss: 3.3373680288243452
Epoch: 5, Loss: 3.195461881312811
Epoch: 6, Loss: 3.0511470691799105
Epoch: 7, Loss: 2.8943985012633107
Epoch: 8, Loss: 2.7294754350378363
Epoch: 9, Loss: 2.556154887639003
Epoch: 10, Loss: 2.377130103493735
Epoch: 11, Loss: 2.2000682491324035
Epoch: 12, Loss: 2.0272005133049067
Epoch: 13, Loss: 1.8560499676572164
Epoch: 14, Loss: 1.68507684621983
Epoch: 15, Loss: 1.5246241512925718
Epoch: 16, Loss: 1.3766878395921063
Epoch: 17, Loss: 1.2434373494344189
Epoch: 18, Loss: 1.127108834824637
Epoch: 19, Loss: 1.0297294027184827
Epoch: 20, Loss: 0.952430289994197
Epoch: 21, Loss: 0.8945001683879341
Epoch: 22, Loss: 0.8532231725729258
Epoch: 23, Loss: 0.8247468032238315
Epoch: 24, Loss: 0.8051591569642892
Epoch: 25, Loss: 0.7912734094473365
Epoch: 26, Loss: 0.7808911796618352
Epoch: 27, Loss: 0.7726496374029523
Epoch: 28, Loss: 0.765749097016048
Epoch: 29, Loss: 0.7597304376538281
Epoch: 30, Loss: 0.7543306711690305
Epoch: 31, Loss: 0.7493973367031886
Epoch: 32, Loss: 0.7448396599772319
Epoch: 33, Loss: 0.7406011707813994
Epoch: 34, Loss: 0.7366444938547304
Epoch: 35, Loss: 0.7329429540435344
Epoch: 36, Loss: 0.7294759667726787
Epoch: 37, Loss: 0.7262265192654985
Epoch: 38, Loss: 0.7231798003424216
Epoch: 39, Loss: 0.720322457526014
Epoch: 40, Loss: 0.7176421944210686
Epoch: 41, Loss: 0.7151275511238498
Epoch: 42, Loss: 0.7127677820064319
Epoch: 43, Loss: 0.7105527845298107
Epoch: 44, Loss: 0.7084730542162745
Epoch: 45, Loss: 0.7065196525859568
Epoch: 46, Loss: 0.7046841811738843
Epoch: 47, Loss: 0.7029587581344647
Epoch: 48, Loss: 0.7013359957471811
Epoch: 49, Loss: 0.6998089780884672
Epoch: 50, Loss: 0.6983712386253578
Epoch: 51, Loss: 0.6970167377300213
Epoch: 52, Loss: 0.6957398402259282
Epoch: 53, Loss: 0.6945352931182873
Epoch: 54, Loss: 0.6933982036670583
Epoch: 55, Loss: 0.6923240179484886
Epoch: 56, Loss: 0.6913085000305985
Epoch: 57, Loss: 0.690347711864669
Epoch: 58, Loss: 0.6894379939715011
Epoch: 59, Loss: 0.6885759469794592
Epoch: 60, Loss: 0.6877584140518346
Epoch: 61, Loss: 0.6869824642241511
Epoch: 62, Loss: 0.6862453766576767
Epoch: 63, Loss: 0.6855446258035237
Epoch: 64, Loss: 0.6848778674620684
Epoch: 65, Loss: 0.6842429257148135
Epoch: 66, Loss: 0.6836377806999588
Epoch: 67, Loss: 0.6830605571986257
Epoch: 68, Loss: 0.6825095139956536
Epoch: 69, Loss: 0.681983033976946
Epoch: 70, Loss: 0.6814796149242904
Epoch: 71, Loss: 0.6809978609682587
Epoch: 72, Loss: 0.6805364746600482
Epoch: 73, Loss: 0.6800942496238422
Epoch: 74, Loss: 0.6796700637523185
Epoch: 75, Loss: 0.6792628729092651
Epoch: 76, Loss: 0.6788717051047596
Epoch: 77, Loss: 0.6784956551099925
Epoch: 78, Loss: 0.6781338794805258
Epoch: 79, Loss: 0.6777855919585002
Epoch: 80, Loss: 0.6774500592260526
Epoch: 81, Loss: 0.6771265969839102
Epoch: 82, Loss: 0.6768145663308129
Epoch: 83, Loss: 0.6765133704210264
Epoch: 84, Loss: 0.6762224513787696
Epoch: 85, Loss: 0.6759412874498607
Epoch: 86, Loss: 0.6756693903722978
Epoch: 87, Loss: 0.6754063029488205
Epoch: 88, Loss: 0.6751515968057485
Epoch: 89, Loss: 0.6749048703235732
Epoch: 90, Loss: 0.6746657467258778
Epoch: 91, Loss: 0.6744338723141834
Epoch: 92, Loss: 0.6742089148372796
Epoch: 93, Loss: 0.6739905619844809
Epoch: 94, Loss: 0.6737785199930812
Epoch: 95, Loss: 0.6735725123610361
Epoch: 96, Loss: 0.6733722786566118
Epoch: 97, Loss: 0.673177573417395
Epoch: 98, Loss: 0.6729881651316577
Epoch: 99, Loss: 0.6728038352956306
Epoch: 100, Loss: 0.6726243775407513

In [26]:
model.bias

tensor([-0.4749], dtype=torch.float64, requires_grad=True)

In [27]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6163434982299805