<a href="https://colab.research.google.com/github/harshs-data/Pytorch/blob/main/training_pipeline_using_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [149]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import torch.optim as optim

In [150]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [151]:
df.shape

(569, 33)

In [152]:
df.drop(columns=['id', 'Unnamed: 32'], inplace = True)
df

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [153]:
df.shape

(569, 31)

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   diagnosis                569 non-null    object
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  569 non-null    float64
 15  smoothness_se            569 non-null    float64
 16  compactness_se           569 non-null    float64
 17  concavity_se             569 non-null    float64
 18  concave points_se        569 non-null    float64
 19  symmetry_se              569 non-null    float64
 20  fractal_dimension_se     569 non-null    float64
 21  radius_worst             569 non-null    float64
 22  texture_worst            569 non-null    float64
 23  perimeter_worst          569 non-null    float64
 24  area_worst               569 non-null    float64
 25  smoothness_worst         569 non-null    float64
 26  compactness_worst        569 non-null    float64
 27  concavity_worst          569 non-null    float64
 28  concave points_worst     569 non-null    float64
 29  symmetry_worst           569 non-null    float64
 30  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), object(1)
memory usage: 137.9+ KB

In [155]:
df.describe()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [156]:
df.isnull().sum()

diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [157]:
df.duplicated().sum()

np.int64(0)

### Train test split

In [158]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2, random_state=42)

In [159]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((455, 30), (114, 30), (455,), (114,))

# scaling

In [160]:
scaler = StandardScaler()
df_train = scaler.fit_transform(X_train)
df_test = scaler.transform(X_test)

### LabelEncoder

In [161]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

### Numpy to pytorch tensors

In [162]:
X_train_tensor = torch.from_numpy(df_train.astype(np.float32))
X_test_tensor = torch.from_numpy(df_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [163]:
X_train_tensor.shape

torch.Size([455, 30])

### Defining the Model

In [164]:
class MysimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

  '''
  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss
    '''

Imp. parameters

In [165]:
learning_rate = 0.1
epochs = 25

In [166]:
# defining loss function
loss_function = nn.BCELoss()

### Training pipeline

In [167]:
# create model
model = MysimpleNN(X_train_tensor.shape[1])

In [168]:
# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

In [169]:
# define loop

for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1)) # Reshape y_train_tensor

  # zero gradients
  '''
  for param in model.parameters():
    if param.grad is not None:
        param.grad.zero_()
  '''
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  '''
  with torch.no_grad():
    for param in model.parameters():
      param -= learning_rate * param.grad
  '''
  optimizer.step()

  # print loss in each epoch

  print(f'Epoch: {epoch + 1}, loss: {loss.item()}')

Epoch: 1, loss: 0.7409963607788086
Epoch: 2, loss: 0.5483359098434448
Epoch: 3, loss: 0.4450143277645111
Epoch: 4, loss: 0.3835028409957886
Epoch: 5, loss: 0.34293368458747864
Epoch: 6, loss: 0.31404536962509155
Epoch: 7, loss: 0.2922704815864563
Epoch: 8, loss: 0.2751363217830658
Epoch: 9, loss: 0.2611997723579407
Epoch: 10, loss: 0.24956512451171875
Epoch: 11, loss: 0.23964811861515045
Epoch: 12, loss: 0.2310514748096466
Epoch: 13, loss: 0.22349543869495392
Epoch: 14, loss: 0.21677716076374054
Epoch: 15, loss: 0.210745707154274
Epoch: 16, loss: 0.20528635382652283
Epoch: 17, loss: 0.20031005144119263
Epoch: 18, loss: 0.19574669003486633
Epoch: 19, loss: 0.1915399432182312
Epoch: 20, loss: 0.18764419853687286
Epoch: 21, loss: 0.1840219497680664
Epoch: 22, loss: 0.18064194917678833
Epoch: 23, loss: 0.17747800052165985
Epoch: 24, loss: 0.17450790107250214
Epoch: 25, loss: 0.17171262204647064

In [170]:
model.linear.weight

Parameter containing:
tensor([[ 0.0703,  0.2124,  0.3259,  0.3678,  0.1480,  0.1023,  0.2501,  0.1463,
          0.0701, -0.1441,  0.3242,  0.0518,  0.1108,  0.2386, -0.1096, -0.1182,
          0.0968,  0.0704, -0.1597, -0.0399,  0.2910,  0.0717,  0.2525,  0.3218,
          0.2360,  0.0546,  0.1554,  0.1326,  0.2756,  0.1775]],
       requires_grad=True)

In [171]:
model.linear.bias

Parameter containing:
tensor([-0.2372], requires_grad=True)

In [172]:
y_pred

tensor([[0.5367],
        [0.9994],
        [0.0213],
        [0.1362],
        [0.0534],
        [0.9572],
        [0.3046],
        [0.0559],
        [0.1124],
        [0.9715],
        [0.2279],
        [0.9901],
        [0.9258],
        [0.0653],
        [0.0967],
        [0.9923],
        [0.9989],
        [0.9812],
        [0.1333],
        [0.0662],
        [0.2217],
        [0.9071],
        [0.3707],
        [0.0691],
        [0.5430],
        [0.8465],
        [0.0883],
        [0.9959],
        [0.0316],
        [0.0263],
        [0.8162],
        [0.0933],
        [0.9698],
        [0.9836],
        [0.5571],
        [0.0634],
        [0.5610],
        [0.0342],
        [0.0115],
        [0.1976],
        [0.0458],
        [1.0000],
        [0.9637],
        [0.0098],
        [0.1750],
        [0.0174],
        [0.0068],
        [0.0601],
        [0.0321],
        [0.1009],
        [0.4822],
        [0.0973],
        [0.0664],
        [0.3301],
        [0.0686],
        [0.8392],
        [0.3408],
        [0.0964],
        [0.0806],
        [0.5022],
        [0.0886],
        [0.1970],
        [0.6009],
        [0.3346],
        [0.1016],
        [0.2487],
        [0.2937],
        [0.1153],
        [0.0519],
        [0.8034],
        [0.9576],
        [0.7958],
        [0.5526],
        [0.2424],
        [0.8743],
        [0.1151],
        [0.9926],
        [0.1238],
        [0.1037],
        [0.0154],
        [0.0551],
        [0.6875],
        [0.2548],
        [0.0208],
        [0.9944],
        [0.0391],
        [0.1111],
        [0.0437],
        [0.9965],
        [0.1210],
        [0.9938],
        [0.9927],
        [0.0453],
        [0.0684],
        [0.2701],
        [0.5481],
        [0.0339],
        [0.0168],
        [0.0879],
        [0.0157],
        [0.8682],
        [0.0592],
        [0.0944],
        [0.0133],
        [0.0426],
        [0.0208],
        [0.8503],
        [0.2623],
        [0.9953],
        [0.9759],
        [0.1323],
        [0.0555],
        [0.9990],
        [0.0896],
        [0.0095],
        [0.1293],
        [0.2486],
        [0.3214],
        [0.0701],
        [0.0745],
        [0.5746],
        [0.8496],
        [0.9999],
        [0.0627],
        [0.1172],
        [0.9957],
        [0.1674],
        [0.0911],
        [0.9289],
        [0.0935],
        [0.7585],
        [0.0104],
        [0.9890],
        [0.1195],
        [0.3312],
        [0.0597],
        [0.4647],
        [0.7253],
        [0.1626],
        [0.0287],
        [0.1636],
        [0.9579],
        [0.1649],
        [0.9626],
        [0.3714],
        [0.9271],
        [0.0557],
        [0.8100],
        [0.0397],
        [0.4558],
        [0.9514],
        [0.1621],
        [0.0062],
        [0.0645],
        [0.0899],
        [0.6854],
        [0.3538],
        [0.0456],
        [0.1225],
        [0.9897],
        [0.4341],
        [0.0772],
        [0.7368],
        [0.6974],
        [0.0630],
        [0.9962],
        [0.0766],
        [0.0246],
        [0.0876],
        [0.1234],
        [0.1021],
        [0.3141],
        [0.0291],
        [0.8137],
        [0.0792],
        [0.1584],
        [0.1482],
        [0.6152],
        [0.0204],
        [0.9620],
        [0.4428],
        [0.1782],
        [0.0577],
        [0.7155],
        [0.0620],
        [0.8493],
        [0.9915],
        [0.0202],
        [0.1601],
        [0.8993],
        [0.0323],
        [0.9038],
        [0.7962],
        [0.1203],
        [0.2297],
        [0.0803],
        [0.3380],
        [0.4911],
        [0.1139],
        [0.0066],
        [0.9676],
        [0.1416],
        [0.6066],
        [0.1859],
        [0.2789],
        [0.1317],
        [1.0000],
        [0.3100],
        [0.9997],
        [0.0693],
        [0.1762],
        [0.9750],
        [0.9896],
        [0.0236],
        [0.0754],
        [0.9790],
        [0.0894],
        [0.9794],
        [0.9999],
        [0.0338],
        [0.9994],
        [0.9989],
        [0.0711],
        [0.4230],
        [0.9640],
        [0.9779],
        [0.9989],
        [0.3321],
        [0.0955],
        [0.1018],
        [0.1213],
        [0.8773],
        [0.0856],
        [0.9506],
        [0.9948],
        [0.9874],
        [0.4379],
        [0.0248],
        [0.1242],
        [0.4516],
        [0.2936],
        [0.1401],
        [0.1269],
        [0.0561],
        [0.1161],
        [0.9419],
        [0.9835],
        [0.5366],
        [0.0327],
        [0.9766],
        [0.0587],
        [0.0747],
        [0.0067],
        [0.1141],
        [0.0246],
        [0.9816],
        [0.0626],
        [0.2389],
        [0.9972],
        [0.9129],
        [0.0995],
        [0.6965],
        [0.1551],
        [0.9960],
        [0.0843],
        [0.1470],
        [0.0760],
        [0.0395],
        [0.1845],
        [0.1470],
        [0.9362],
        [0.0177],
        [0.2978],
        [0.9071],
        [0.1714],
        [0.0348],
        [0.0342],
        [0.1069],
        [0.0870],
        [0.2250],
        [0.9926],
        [0.3833],
        [0.2864],
        [0.5757],
        [0.2137],
        [0.8229],
        [0.8493],
        [0.9709],
        [0.3345],
        [0.8141],
        [0.2756],
        [0.0248],
        [0.9881],
        [0.9500],
        [0.9713],
        [0.0881],
        [0.0849],
        [0.1553],
        [0.0642],
        [0.2912],
        [0.2478],
        [0.0995],
        [0.9857],
        [0.0768],
        [0.1439],
        [0.2867],
        [0.9390],
        [0.0294],
        [0.0320],
        [0.8430],
        [0.4494],
        [0.0326],
        [0.9113],
        [0.0392],
        [0.9676],
        [0.9791],
        [0.0188],
        [0.0868],
        [0.9874],
        [0.1882],
        [0.9662],
        [0.9955],
        [0.0668],
        [0.9135],
        [0.5262],
        [0.0358],
        [0.3324],
        [0.5424],
        [0.0567],
        [0.4793],
        [0.0716],
        [0.1686],
        [0.5865],
        [0.0462],
        [0.3616],
        [0.7844],
        [0.9815],
        [0.9931],
        [0.1386],
        [0.0261],
        [0.2206],
        [0.9533],
        [0.9373],
        [0.1006],
        [0.9483],
        [0.9871],
        [0.1700],
        [0.0837],
        [0.0721],
        [0.9977],
        [0.0229],
        [0.9557],
        [0.9006],
        [0.9219],
        [0.2088],
        [0.4901],
        [0.1148],
        [0.8790],
        [0.0876],
        [0.1107],
        [0.8105],
        [0.9976],
        [0.8744],
        [0.9510],
        [0.2267],
        [0.8491],
        [0.0801],
        [0.0175],
        [0.1940],
        [0.1559],
        [0.1888],
        [0.0506],
        [0.0303],
        [0.9854],
        [0.9998],
        [0.7524],
        [1.0000],
        [0.0718],
        [0.3303],
        [0.0719],
        [0.3167],
        [1.0000],
        [0.2557],
        [0.7502],
        [0.0354],
        [0.0356],
        [0.0976],
        [0.1762],
        [0.1602],
        [0.8479],
        [0.9296],
        [0.7077],
        [0.0430],
        [0.0682],
        [0.8806],
        [0.3296],
        [0.0530],
        [0.9739],
        [0.8755],
        [0.9615],
        [0.9585],
        [0.0975],
        [0.1688],
        [0.5623],
        [0.9350],
        [0.3231],
        [0.1194],
        [0.1232],
        [0.9925],
        [0.4245],
        [0.9997],
        [0.0176],
        [0.0345],
        [0.4637],
        [0.0256],
        [0.0673],
        [0.0304],
        [0.0198],
        [0.9990],
        [0.4507],
        [0.1568],
        [0.1999],
        [0.1694],
        [0.0471],
        [0.1507],
        [0.0469],
        [0.0559],
        [0.0821],
        [0.9966],
        [0.0207],
        [0.0294],
        [0.0347],
        [0.2209],
        [0.0265],
        [0.1142],
        [0.4310],
        [0.5068],
        [0.3563],
        [0.9859],
        [0.0336],
        [0.1109],
        [0.5370],
        [0.9590],
        [0.9821],
        [0.1191],
        [0.7732],
        [0.7806],
        [0.3127],
        [0.9601],
        [0.1791],
        [0.0125],
        [0.2766],
        [0.0398],
        [0.6828],
        [0.0803]], grad_fn=<SigmoidBackward0>)

# Evaluation

In [173]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5301631093025208

In [174]:
y_pred

tensor([[0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.]])