<a href="https://colab.research.google.com/github/harshs-data/Pytorch/blob/main/training_pipeline_using_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import torch.optim as optim

In [13]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [14]:
df.shape

(569, 33)

In [15]:
df.drop(columns=['id', 'Unnamed: 32'], inplace = True)
df

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [17]:
df.shape

(569, 31)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   diagnosis                569 non-null    object
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  569 non-null    float64
 15  smoothness_se            569 non-null    float64
 16  compactness_se           569 non-null    float64
 17  concavity_se             569 non-null    float64
 18  concave points_se        569 non-null    float64
 19  symmetry_se              569 non-null    float64
 20  fractal_dimension_se     569 non-null    float64
 21  radius_worst             569 non-null    float64
 22  texture_worst            569 non-null    float64
 23  perimeter_worst          569 non-null    float64
 24  area_worst               569 non-null    float64
 25  smoothness_worst         569 non-null    float64
 26  compactness_worst        569 non-null    float64
 27  concavity_worst          569 non-null    float64
 28  concave points_worst     569 non-null    float64
 29  symmetry_worst           569 non-null    float64
 30  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), object(1)
memory usage: 137.9+ KB

In [19]:
df.describe()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [20]:
df.isnull().sum()

diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [21]:
df.duplicated().sum()

np.int64(0)

### Train test split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2, random_state=42)

In [23]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((455, 30), (114, 30), (455,), (114,))

# scaling

In [24]:
scaler = StandardScaler()
df_train = scaler.fit_transform(X_train)
df_test = scaler.transform(X_test)

### LabelEncoder

In [25]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

### Numpy to pytorch tensors

In [26]:
X_train_tensor = torch.from_numpy(df_train.astype(np.float32))
X_test_tensor = torch.from_numpy(df_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [27]:
X_train_tensor.shape

torch.Size([455, 30])

### Creating batches

In [66]:
from torch.utils.data import Dataset, DataLoader

In [67]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [68]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [70]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

### Defining the Model

In [33]:
class MysimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

  '''
  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss
    '''

Imp. parameters

In [48]:
learning_rate = 0.1
epochs = 25

In [49]:
# defining loss function
loss_function = nn.BCELoss()

### Training pipeline

In [50]:
# create model
model = MysimpleNN(X_train_tensor.shape[1])

In [51]:
# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

In [58]:
# define loop

for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(X_train_tensor)

    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1,1)) # Reshape y_train_tensor

    # zero gradients
    '''
    for param in model.parameters():
      if param.grad is not None:
          param.grad.zero_()
    '''
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    '''
    with torch.no_grad():
      for param in model.parameters():
        param -= learning_rate * param.grad
    '''
    optimizer.step()

    # print loss in each epoch

    print(f'Epoch: {epoch+1}/{epochs}, Loss: {loss.item()}')

Epoch: 1/25, Loss: 0.0748746395111084
Epoch: 1/25, Loss: 0.07482954114675522
Epoch: 1/25, Loss: 0.07478459924459457
Epoch: 1/25, Loss: 0.07473984360694885
Epoch: 1/25, Loss: 0.07469525188207626
Epoch: 1/25, Loss: 0.0746508240699768
Epoch: 1/25, Loss: 0.07460658252239227
Epoch: 1/25, Loss: 0.07456249743700027
Epoch: 1/25, Loss: 0.074518583714962
Epoch: 1/25, Loss: 0.07447484135627747
Epoch: 1/25, Loss: 0.07443124800920486
Epoch: 1/25, Loss: 0.07438782602548599
Epoch: 1/25, Loss: 0.07434457540512085
Epoch: 1/25, Loss: 0.07430148124694824
Epoch: 1/25, Loss: 0.07425855100154877
Epoch: 2/25, Loss: 0.07421577721834183
Epoch: 2/25, Loss: 0.07417315244674683
Epoch: 2/25, Loss: 0.07413069158792496
Epoch: 2/25, Loss: 0.07408839464187622
Epoch: 2/25, Loss: 0.07404624670743942
Epoch: 2/25, Loss: 0.07400424778461456
Epoch: 2/25, Loss: 0.07396241277456284
Epoch: 2/25, Loss: 0.07392072677612305
Epoch: 2/25, Loss: 0.0738791897892952
Epoch: 2/25, Loss: 0.07383780926465988
Epoch: 2/25, Loss: 0.07379657030105591
Epoch: 2/25, Loss: 0.07375548779964447
Epoch: 2/25, Loss: 0.07371454685926437
Epoch: 2/25, Loss: 0.07367376238107681
Epoch: 2/25, Loss: 0.07363311201334
Epoch: 3/25, Loss: 0.07359260320663452
Epoch: 3/25, Loss: 0.07355225831270218
Epoch: 3/25, Loss: 0.07351204007863998
Epoch: 3/25, Loss: 0.07347197830677032
Epoch: 3/25, Loss: 0.07343204319477081
Epoch: 3/25, Loss: 0.07339224964380264
Epoch: 3/25, Loss: 0.07335260510444641
Epoch: 3/25, Loss: 0.07331308722496033
Epoch: 3/25, Loss: 0.07327372580766678
Epoch: 3/25, Loss: 0.07323449105024338
Epoch: 3/25, Loss: 0.07319539785385132
Epoch: 3/25, Loss: 0.07315643876791
Epoch: 3/25, Loss: 0.07311761379241943
Epoch: 3/25, Loss: 0.07307890802621841
Epoch: 3/25, Loss: 0.07304035127162933
Epoch: 4/25, Loss: 0.0730019211769104
Epoch: 4/25, Loss: 0.07296362519264221
Epoch: 4/25, Loss: 0.07292546331882477
Epoch: 4/25, Loss: 0.07288742810487747
Epoch: 4/25, Loss: 0.07284951955080032
Epoch: 4/25, Loss: 0.07281173765659332
Epoch: 4/25, Loss: 0.07277408987283707
Epoch: 4/25, Loss: 0.07273656129837036
Epoch: 4/25, Loss: 0.0726991593837738
Epoch: 4/25, Loss: 0.07266189903020859
Epoch: 4/25, Loss: 0.07262475043535233
Epoch: 4/25, Loss: 0.07258772850036621
Epoch: 4/25, Loss: 0.07255081087350845
Epoch: 4/25, Loss: 0.07251404225826263
Epoch: 4/25, Loss: 0.07247738540172577
Epoch: 5/25, Loss: 0.07244085520505905
Epoch: 5/25, Loss: 0.07240443676710129
Epoch: 5/25, Loss: 0.07236813753843307
Epoch: 5/25, Loss: 0.07233196496963501
Epoch: 5/25, Loss: 0.07229591906070709
Epoch: 5/25, Loss: 0.07225997745990753
Epoch: 5/25, Loss: 0.07222414761781693
Epoch: 5/25, Loss: 0.07218844443559647
Epoch: 5/25, Loss: 0.07215285301208496
Epoch: 5/25, Loss: 0.07211737334728241
Epoch: 5/25, Loss: 0.07208201289176941
Epoch: 5/25, Loss: 0.07204677164554596
Epoch: 5/25, Loss: 0.07201163470745087
Epoch: 5/25, Loss: 0.07197660207748413
Epoch: 5/25, Loss: 0.07194170355796814
Epoch: 6/25, Loss: 0.07190690189599991
Epoch: 6/25, Loss: 0.07187220454216003
Epoch: 6/25, Loss: 0.07183763384819031
Epoch: 6/25, Loss: 0.07180316746234894
Epoch: 6/25, Loss: 0.07176880538463593
Epoch: 6/25, Loss: 0.07173456251621246
Epoch: 6/25, Loss: 0.07170040905475616
Epoch: 6/25, Loss: 0.07166637480258942
Epoch: 6/25, Loss: 0.07163244485855103
Epoch: 6/25, Loss: 0.0715986117720604
Epoch: 6/25, Loss: 0.07156490534543991
Epoch: 6/25, Loss: 0.071531280875206
Epoch: 6/25, Loss: 0.07149777561426163
Epoch: 6/25, Loss: 0.07146435976028442
Epoch: 6/25, Loss: 0.07143105566501617
Epoch: 7/25, Loss: 0.07139786332845688
Epoch: 7/25, Loss: 0.07136475294828415
Epoch: 7/25, Loss: 0.07133175432682037
Epoch: 7/25, Loss: 0.07129885256290436
Epoch: 7/25, Loss: 0.0712660476565361
Epoch: 7/25, Loss: 0.0712333619594574
Epoch: 7/25, Loss: 0.07120076566934586
Epoch: 7/25, Loss: 0.07116825878620148
Epoch: 7/25, Loss: 0.07113585621118546
Epoch: 7/25, Loss: 0.0711035504937172
Epoch: 7/25, Loss: 0.07107134163379669
Epoch: 7/25, Loss: 0.07103922963142395
Epoch: 7/25, Loss: 0.07100722193717957
Epoch: 7/25, Loss: 0.07097529619932175
Epoch: 7/25, Loss: 0.07094346731901169
Epoch: 8/25, Loss: 0.07091173529624939
Epoch: 8/25, Loss: 0.07088010013103485
Epoch: 8/25, Loss: 0.07084856182336807
Epoch: 8/25, Loss: 0.07081711292266846
Epoch: 8/25, Loss: 0.0707857608795166
Epoch: 8/25, Loss: 0.07075448334217072
Epoch: 8/25, Loss: 0.07072331011295319
Epoch: 8/25, Loss: 0.07069223374128342
Epoch: 8/25, Loss: 0.07066123932600021
Epoch: 8/25, Loss: 0.07063033431768417
Epoch: 8/25, Loss: 0.07059954106807709
Epoch: 8/25, Loss: 0.07056880742311478
Epoch: 8/25, Loss: 0.07053817063570023
Epoch: 8/25, Loss: 0.07050763070583344
Epoch: 8/25, Loss: 0.07047717273235321
Epoch: 9/25, Loss: 0.07044680416584015
Epoch: 9/25, Loss: 0.07041651755571365
Epoch: 9/25, Loss: 0.07038632780313492
Epoch: 9/25, Loss: 0.07035621255636215
Epoch: 9/25, Loss: 0.07032619416713715
Epoch: 9/25, Loss: 0.0702962577342987
Epoch: 9/25, Loss: 0.07026639580726624
Epoch: 9/25, Loss: 0.07023664563894272
Epoch: 9/25, Loss: 0.07020695507526398
Epoch: 9/25, Loss: 0.0701773390173912
Epoch: 9/25, Loss: 0.07014783471822739
Epoch: 9/25, Loss: 0.07011839747428894
Epoch: 9/25, Loss: 0.07008904218673706
Epoch: 9/25, Loss: 0.07005977630615234
Epoch: 9/25, Loss: 0.0700305923819542
Epoch: 10/25, Loss: 0.07000147551298141
Epoch: 10/25, Loss: 0.0699724480509758
Epoch: 10/25, Loss: 0.06994350254535675
Epoch: 10/25, Loss: 0.06991463154554367
Epoch: 10/25, Loss: 0.06988584995269775
Epoch: 10/25, Loss: 0.0698571428656578
Epoch: 10/25, Loss: 0.06982852518558502
Epoch: 10/25, Loss: 0.06979997456073761
Epoch: 10/25, Loss: 0.06977149844169617
Epoch: 10/25, Loss: 0.06974310427904129
Epoch: 10/25, Loss: 0.06971479207277298
Epoch: 10/25, Loss: 0.06968653947114944
Epoch: 10/25, Loss: 0.06965838372707367
Epoch: 10/25, Loss: 0.06963029503822327
Epoch: 10/25, Loss: 0.06960228830575943
Epoch: 11/25, Loss: 0.06957434862852097
Epoch: 11/25, Loss: 0.06954649835824966
Epoch: 11/25, Loss: 0.06951870769262314
Epoch: 11/25, Loss: 0.06949099153280258
Epoch: 11/25, Loss: 0.06946335732936859
Epoch: 11/25, Loss: 0.06943580508232117
Epoch: 11/25, Loss: 0.06940830498933792
Epoch: 11/25, Loss: 0.06938089430332184
Epoch: 11/25, Loss: 0.06935355067253113
Epoch: 11/25, Loss: 0.06932628154754639
Epoch: 11/25, Loss: 0.06929907947778702
Epoch: 11/25, Loss: 0.06927195191383362
Epoch: 11/25, Loss: 0.06924489885568619
Epoch: 11/25, Loss: 0.06921791285276413
Epoch: 11/25, Loss: 0.06919100135564804
Epoch: 12/25, Loss: 0.06916415691375732
Epoch: 12/25, Loss: 0.06913737952709198
Epoch: 12/25, Loss: 0.0691106766462326
Epoch: 12/25, Loss: 0.0690840482711792
Epoch: 12/25, Loss: 0.06905748695135117
Epoch: 12/25, Loss: 0.06903098523616791
Epoch: 12/25, Loss: 0.06900456547737122
Epoch: 12/25, Loss: 0.0689781978726387
Epoch: 12/25, Loss: 0.06895191222429276
Epoch: 12/25, Loss: 0.06892568618059158
Epoch: 12/25, Loss: 0.06889952719211578
Epoch: 12/25, Loss: 0.06887344270944595
Epoch: 12/25, Loss: 0.0688474103808403
Epoch: 12/25, Loss: 0.06882146000862122
Epoch: 12/25, Loss: 0.0687955692410469
Epoch: 13/25, Loss: 0.06876974552869797
Epoch: 13/25, Loss: 0.0687439814209938
Epoch: 13/25, Loss: 0.06871829181909561
Epoch: 13/25, Loss: 0.0686926543712616
Epoch: 13/25, Loss: 0.06866709887981415
Epoch: 13/25, Loss: 0.06864159554243088
Epoch: 13/25, Loss: 0.06861615926027298
Epoch: 13/25, Loss: 0.06859079003334045
Epoch: 13/25, Loss: 0.0685654804110527
Epoch: 13/25, Loss: 0.06854023039340973
Epoch: 13/25, Loss: 0.06851505488157272
Epoch: 13/25, Loss: 0.0684899315237999
Epoch: 13/25, Loss: 0.06846487522125244
Epoch: 13/25, Loss: 0.06843988597393036
Epoch: 13/25, Loss: 0.06841494888067245
Epoch: 14/25, Loss: 0.06839007884263992
Epoch: 14/25, Loss: 0.06836526840925217
Epoch: 14/25, Loss: 0.06834051012992859
Epoch: 14/25, Loss: 0.06831582635641098
Epoch: 14/25, Loss: 0.06829120218753815
Epoch: 14/25, Loss: 0.06826663017272949
Epoch: 14/25, Loss: 0.06824211776256561
Epoch: 14/25, Loss: 0.0682176798582077
Epoch: 14/25, Loss: 0.06819328665733337
Epoch: 14/25, Loss: 0.06816896051168442
Epoch: 14/25, Loss: 0.06814468652009964
Epoch: 14/25, Loss: 0.06812047213315964
Epoch: 14/25, Loss: 0.06809631735086441
Epoch: 14/25, Loss: 0.06807221472263336
Epoch: 14/25, Loss: 0.06804818660020828
Epoch: 15/25, Loss: 0.06802420318126678
Epoch: 15/25, Loss: 0.06800028681755066
Epoch: 15/25, Loss: 0.06797642260789871
Epoch: 15/25, Loss: 0.06795261800289154
Epoch: 15/25, Loss: 0.06792885810136795
Epoch: 15/25, Loss: 0.06790517270565033
Epoch: 15/25, Loss: 0.06788153946399689
Epoch: 15/25, Loss: 0.06785795092582703
Epoch: 15/25, Loss: 0.06783441454172134
Epoch: 15/25, Loss: 0.06781094521284103
Epoch: 15/25, Loss: 0.0677875429391861
Epoch: 15/25, Loss: 0.06776417046785355
Epoch: 15/25, Loss: 0.06774086505174637
Epoch: 15/25, Loss: 0.06771761924028397
Epoch: 15/25, Loss: 0.06769442558288574
Epoch: 16/25, Loss: 0.0676712840795517
Epoch: 16/25, Loss: 0.06764818727970123
Epoch: 16/25, Loss: 0.06762516498565674
Epoch: 16/25, Loss: 0.06760217994451523
Epoch: 16/25, Loss: 0.0675792545080185
Epoch: 16/25, Loss: 0.06755637377500534
Epoch: 16/25, Loss: 0.06753355264663696
Epoch: 16/25, Loss: 0.06751078367233276
Epoch: 16/25, Loss: 0.06748807430267334
Epoch: 16/25, Loss: 0.0674654170870781
Epoch: 16/25, Loss: 0.06744279712438583
Epoch: 16/25, Loss: 0.06742023676633835
Epoch: 16/25, Loss: 0.06739772856235504
Epoch: 16/25, Loss: 0.06737527251243591
Epoch: 16/25, Loss: 0.06735286861658096
Epoch: 17/25, Loss: 0.067330501973629
Epoch: 17/25, Loss: 0.0673082023859024
Epoch: 17/25, Loss: 0.06728595495223999
Epoch: 17/25, Loss: 0.06726374477148056
Epoch: 17/25, Loss: 0.0672415941953659
Epoch: 17/25, Loss: 0.06721950322389603
Epoch: 17/25, Loss: 0.06719744205474854
Epoch: 17/25, Loss: 0.06717544049024582
Epoch: 17/25, Loss: 0.06715349107980728
Epoch: 17/25, Loss: 0.06713158637285233
Epoch: 17/25, Loss: 0.06710973381996155
Epoch: 17/25, Loss: 0.06708792597055435
Epoch: 17/25, Loss: 0.06706617027521133
Epoch: 17/25, Loss: 0.0670444592833519
Epoch: 17/25, Loss: 0.06702280044555664
Epoch: 18/25, Loss: 0.06700117886066437
Epoch: 18/25, Loss: 0.06697960942983627
Epoch: 18/25, Loss: 0.06695809215307236
Epoch: 18/25, Loss: 0.06693662703037262
Epoch: 18/25, Loss: 0.06691519916057587
Epoch: 18/25, Loss: 0.06689383089542389
Epoch: 18/25, Loss: 0.0668724998831749
Epoch: 18/25, Loss: 0.06685121357440948
Epoch: 18/25, Loss: 0.06682997196912766
Epoch: 18/25, Loss: 0.0668087899684906
Epoch: 18/25, Loss: 0.06678764522075653
Epoch: 18/25, Loss: 0.06676656007766724
Epoch: 18/25, Loss: 0.06674550473690033
Epoch: 18/25, Loss: 0.0667245015501976
Epoch: 18/25, Loss: 0.06670353561639786
Epoch: 19/25, Loss: 0.06668262928724289
Epoch: 19/25, Loss: 0.06666175276041031
Epoch: 19/25, Loss: 0.0666409358382225
Epoch: 19/25, Loss: 0.06662015616893768
Epoch: 19/25, Loss: 0.06659942120313644
Epoch: 19/25, Loss: 0.06657873839139938
Epoch: 19/25, Loss: 0.06655809283256531
Epoch: 19/25, Loss: 0.06653748452663422
Epoch: 19/25, Loss: 0.0665169283747673
Epoch: 19/25, Loss: 0.06649641692638397
Epoch: 19/25, Loss: 0.06647594273090363
Epoch: 19/25, Loss: 0.06645552068948746
Epoch: 19/25, Loss: 0.06643513590097427
Epoch: 19/25, Loss: 0.06641479581594467
Epoch: 19/25, Loss: 0.06639449298381805
Epoch: 20/25, Loss: 0.06637424230575562
Epoch: 20/25, Loss: 0.06635403633117676
Epoch: 20/25, Loss: 0.06633387506008148
Epoch: 20/25, Loss: 0.066313736140728
Epoch: 20/25, Loss: 0.06629365682601929
Epoch: 20/25, Loss: 0.06627361476421356
Epoch: 20/25, Loss: 0.06625360995531082
Epoch: 20/25, Loss: 0.06623365730047226
Epoch: 20/25, Loss: 0.06621373444795609
Epoch: 20/25, Loss: 0.06619386374950409
Epoch: 20/25, Loss: 0.06617403030395508
Epoch: 20/25, Loss: 0.06615423411130905
Epoch: 20/25, Loss: 0.0661344900727272
Epoch: 20/25, Loss: 0.06611477583646774
Epoch: 20/25, Loss: 0.06609510630369186
Epoch: 21/25, Loss: 0.06607547402381897
Epoch: 21/25, Loss: 0.06605589389801025
Epoch: 21/25, Loss: 0.06603634357452393
Epoch: 21/25, Loss: 0.06601683795452118
Epoch: 21/25, Loss: 0.06599736213684082
Epoch: 21/25, Loss: 0.06597793847322464
Epoch: 21/25, Loss: 0.06595854461193085
Epoch: 21/25, Loss: 0.06593919545412064
Epoch: 21/25, Loss: 0.065919890999794
Epoch: 21/25, Loss: 0.06590061634778976
Epoch: 21/25, Loss: 0.0658813863992691
Epoch: 21/25, Loss: 0.06586220115423203
Epoch: 21/25, Loss: 0.06584304571151733
Epoch: 21/25, Loss: 0.06582392007112503
Epoch: 21/25, Loss: 0.0658048465847969
Epoch: 22/25, Loss: 0.06578581780195236
Epoch: 22/25, Loss: 0.06576681137084961
Epoch: 22/25, Loss: 0.06574785709381104
Epoch: 22/25, Loss: 0.06572892516851425
Epoch: 22/25, Loss: 0.06571004539728165
Epoch: 22/25, Loss: 0.06569120287895203
Epoch: 22/25, Loss: 0.0656723901629448
Epoch: 22/25, Loss: 0.06565362215042114
Epoch: 22/25, Loss: 0.06563488394021988
Epoch: 22/25, Loss: 0.0656161829829216
Epoch: 22/25, Loss: 0.0655975267291069
Epoch: 22/25, Loss: 0.0655789002776146
Epoch: 22/25, Loss: 0.06556031107902527
Epoch: 22/25, Loss: 0.06554176658391953
Epoch: 22/25, Loss: 0.06552325189113617
Epoch: 23/25, Loss: 0.0655047744512558
Epoch: 23/25, Loss: 0.06548633426427841
Epoch: 23/25, Loss: 0.06546792387962341
Epoch: 23/25, Loss: 0.065449558198452
Epoch: 23/25, Loss: 0.06543122977018356
Epoch: 23/25, Loss: 0.06541293859481812
Epoch: 23/25, Loss: 0.06539467722177505
Epoch: 23/25, Loss: 0.06537645310163498
Epoch: 23/25, Loss: 0.06535825878381729
Epoch: 23/25, Loss: 0.06534010916948318
Epoch: 23/25, Loss: 0.06532198935747147
Epoch: 23/25, Loss: 0.06530390679836273
Epoch: 23/25, Loss: 0.06528585404157639
Epoch: 23/25, Loss: 0.06526783853769302
Epoch: 23/25, Loss: 0.06524986773729324
Epoch: 24/25, Loss: 0.06523191183805466
Epoch: 24/25, Loss: 0.06521400809288025
Epoch: 24/25, Loss: 0.06519613415002823
Epoch: 24/25, Loss: 0.0651782974600792
Epoch: 24/25, Loss: 0.06516047567129135
Epoch: 24/25, Loss: 0.06514272093772888
Epoch: 24/25, Loss: 0.06512497365474701
Epoch: 24/25, Loss: 0.06510727107524872
Epoch: 24/25, Loss: 0.06508959084749222
Epoch: 24/25, Loss: 0.0650719627737999
Epoch: 24/25, Loss: 0.06505436450242996
Epoch: 24/25, Loss: 0.06503678113222122
Epoch: 24/25, Loss: 0.06501924991607666
Epoch: 24/25, Loss: 0.06500174850225449
Epoch: 24/25, Loss: 0.0649842768907547
Epoch: 25/25, Loss: 0.0649668425321579
Epoch: 25/25, Loss: 0.06494943052530289
Epoch: 25/25, Loss: 0.06493206322193146
Epoch: 25/25, Loss: 0.06491471827030182
Epoch: 25/25, Loss: 0.06489741057157516
Epoch: 25/25, Loss: 0.0648801326751709
Epoch: 25/25, Loss: 0.06486289203166962
Epoch: 25/25, Loss: 0.06484568119049072
Epoch: 25/25, Loss: 0.06482850015163422
Epoch: 25/25, Loss: 0.06481136381626129
Epoch: 25/25, Loss: 0.06479424983263016
Epoch: 25/25, Loss: 0.06477716565132141
Epoch: 25/25, Loss: 0.06476011872291565
Epoch: 25/25, Loss: 0.06474309414625168
Epoch: 25/25, Loss: 0.06472611427307129

In [60]:
model.linear.weight

Parameter containing:
tensor([[ 0.4761,  0.6271,  0.5410,  0.4766,  0.1964, -0.1114,  0.7007,  0.7662,
          0.0024, -0.3192,  0.7293,  0.0091,  0.6564,  0.5497,  0.2015, -0.5203,
         -0.0574,  0.0824, -0.3884, -0.5074,  0.8655,  0.9151,  0.7170,  0.6561,
          0.5954,  0.2637,  0.5173,  0.6180,  0.8602,  0.1006]],
       requires_grad=True)

In [61]:
model.linear.bias

Parameter containing:
tensor([-0.5809], requires_grad=True)

In [62]:
y_pred

tensor([[2.9249e-02],
        [1.0000e+00],
        [1.0207e-05],
        [4.2879e-02],
        [9.1093e-05],
        [9.9980e-01],
        [6.0649e-04],
        [6.9241e-04],
        [5.7352e-03],
        [9.9985e-01],
        [7.0741e-02],
        [1.0000e+00],
        [9.9881e-01],
        [9.8055e-04],
        [2.5818e-03],
        [1.0000e+00],
        [1.0000e+00],
        [9.9999e-01],
        [1.1162e-02],
        [2.1873e-03],
        [2.1712e-02],
        [9.9126e-01],
        [2.4193e-01],
        [9.0136e-03],
        [2.2885e-01],
        [9.9665e-01],
        [2.8341e-03],
        [1.0000e+00],
        [5.5020e-05],
        [4.9925e-05],
        [9.8785e-01],
        [1.6490e-03],
        [9.9998e-01],
        [9.9999e-01],
        [6.8067e-01],
        [4.7850e-04],
        [8.9329e-01],
        [1.9912e-04],
        [1.4383e-05],
        [3.7856e-02],
        [1.5369e-03],
        [1.0000e+00],
        [9.9991e-01],
        [5.4570e-05],
        [1.4657e-02],
        [2.9421e-05],
        [8.3503e-07],
        [3.5956e-04],
        [3.9091e-04],
        [2.8696e-03],
        [9.0412e-01],
        [9.3135e-04],
        [1.3237e-03],
        [3.4088e-01],
        [3.1753e-05],
        [9.8388e-01],
        [1.6992e-02],
        [2.1793e-03],
        [1.1720e-03],
        [1.5661e-01],
        [2.7338e-03],
        [4.9279e-02],
        [9.0721e-01],
        [5.9601e-02],
        [2.7926e-03],
        [2.3967e-02],
        [8.8443e-02],
        [3.7632e-02],
        [2.5473e-04],
        [9.7617e-01],
        [9.9937e-01],
        [9.5321e-01],
        [6.6698e-01],
        [5.9920e-02],
        [9.7524e-01],
        [1.6394e-03],
        [1.0000e+00],
        [9.8337e-03],
        [1.9547e-03],
        [7.3642e-05],
        [1.0556e-03],
        [9.5321e-01],
        [1.8513e-01],
        [8.8084e-05],
        [9.9999e-01],
        [1.2378e-04],
        [7.6018e-03],
        [2.9296e-04],
        [1.0000e+00],
        [3.9698e-03],
        [1.0000e+00],
        [1.0000e+00],
        [2.8187e-04],
        [2.4666e-03],
        [7.1071e-02],
        [9.3414e-01],
        [1.1430e-04],
        [3.5831e-05],
        [6.1342e-04],
        [2.5651e-05],
        [9.8631e-01],
        [1.9688e-04],
        [2.6056e-03],
        [1.0997e-05],
        [2.6917e-04],
        [4.7095e-05],
        [9.9040e-01],
        [1.3091e-01],
        [1.0000e+00],
        [9.9996e-01],
        [6.5728e-03],
        [1.6071e-03],
        [1.0000e+00],
        [6.7907e-03],
        [1.4306e-06],
        [2.8066e-02],
        [2.3919e-02],
        [5.5654e-02],
        [8.8805e-03],
        [2.4297e-03],
        [8.1904e-01],
        [9.9433e-01],
        [1.0000e+00],
        [7.7609e-05],
        [9.5466e-03],
        [1.0000e+00],
        [9.0452e-03],
        [4.0755e-03],
        [9.9913e-01],
        [5.1215e-03],
        [8.9769e-01],
        [3.3520e-06],
        [9.9999e-01],
        [1.4976e-03],
        [3.6194e-01],
        [9.8772e-04],
        [2.2944e-01],
        [9.8428e-01],
        [8.0900e-03],
        [1.4963e-04],
        [1.7132e-02],
        [9.9843e-01],
        [1.2255e-02],
        [9.9995e-01],
        [1.8537e-01],
        [9.9935e-01],
        [1.5115e-03],
        [9.7022e-01],
        [2.2830e-04],
        [4.1227e-01],
        [9.9970e-01],
        [1.0724e-01],
        [1.3881e-06],
        [3.2317e-04],
        [7.0986e-04],
        [9.1641e-01],
        [1.1101e-01],
        [1.3811e-03],
        [2.8689e-03],
        [1.0000e+00],
        [4.1344e-01],
        [3.0694e-03],
        [9.7786e-01],
        [6.9004e-04],
        [3.6123e-05],
        [1.0000e+00],
        [1.2050e-03],
        [1.6033e-04],
        [3.3254e-03],
        [6.7389e-03],
        [3.1304e-03],
        [7.8540e-02],
        [9.3060e-05],
        [9.9381e-01],
        [4.8477e-04],
        [2.3308e-02],
        [1.5623e-02],
        [8.6931e-01],
        [3.0692e-05],
        [9.9991e-01],
        [4.8445e-01],
        [7.0336e-02],
        [9.9654e-04],
        [9.5170e-01],
        [2.8976e-04],
        [9.9245e-01],
        [1.0000e+00],
        [2.6407e-05],
        [1.4437e-02],
        [9.9857e-01],
        [2.8474e-04],
        [9.9538e-01],
        [9.5450e-01],
        [5.8772e-03],
        [3.8548e-02],
        [1.4127e-03],
        [1.7941e-01],
        [6.4638e-01],
        [1.2501e-02],
        [2.9383e-06],
        [9.9993e-01],
        [9.8495e-04],
        [6.8057e-01],
        [3.1021e-02],
        [1.2655e-02],
        [6.1174e-02],
        [1.0000e+00],
        [2.4684e-02],
        [1.0000e+00],
        [4.7264e-04],
        [2.1063e-02],
        [1.0000e+00],
        [1.0000e+00],
        [8.2455e-05],
        [1.3398e-03],
        [9.9996e-01],
        [6.7124e-03],
        [9.9997e-01],
        [1.0000e+00],
        [3.8504e-05],
        [1.0000e+00],
        [1.0000e+00],
        [2.6540e-03],
        [8.7757e-02],
        [9.9991e-01],
        [9.9995e-01],
        [1.0000e+00],
        [1.0906e-02],
        [4.1064e-04],
        [3.2878e-03],
        [2.4644e-03],
        [9.9644e-01],
        [1.4713e-03],
        [9.9858e-01],
        [1.0000e+00],
        [9.9999e-01],
        [5.2820e-01],
        [1.7967e-05],
        [3.8184e-03],
        [9.6389e-02],
        [4.3821e-02],
        [1.8892e-02],
        [1.4763e-02],
        [3.4775e-04],
        [2.5679e-02],
        [9.9990e-01],
        [9.9999e-01],
        [3.7866e-02],
        [8.3126e-05],
        [9.9999e-01],
        [2.9843e-03],
        [3.4232e-03],
        [5.9314e-06],
        [6.7985e-04],
        [5.6024e-05],
        [9.9999e-01],
        [3.6929e-04],
        [7.9684e-03],
        [1.0000e+00],
        [9.9821e-01],
        [2.7524e-03],
        [7.9486e-01],
        [1.6655e-02],
        [1.0000e+00],
        [2.5340e-02],
        [1.2211e-02],
        [7.9796e-04],
        [5.3786e-04],
        [5.8434e-04],
        [1.6380e-02],
        [9.9924e-01],
        [2.9282e-05],
        [6.8806e-02],
        [9.9736e-01],
        [4.8352e-02],
        [2.2700e-04],
        [2.1311e-04],
        [5.7175e-04],
        [5.0214e-03],
        [2.9237e-01],
        [9.9999e-01],
        [1.6069e-01],
        [7.7349e-02],
        [8.8386e-01],
        [2.9608e-02],
        [9.9475e-01],
        [9.7387e-01],
        [9.9993e-01],
        [2.2844e-02],
        [9.9142e-01],
        [3.3373e-02],
        [6.9709e-05],
        [9.9973e-01],
        [9.9984e-01],
        [9.9999e-01],
        [1.4362e-03],
        [1.6347e-03],
        [1.0841e-02],
        [2.6529e-03],
        [1.4456e-01],
        [1.6743e-02],
        [5.5662e-03],
        [9.9999e-01],
        [1.6307e-03],
        [9.5381e-03],
        [4.1299e-02],
        [9.9639e-01],
        [3.5955e-04],
        [5.6474e-04],
        [9.6300e-01],
        [7.1666e-01],
        [6.0217e-05],
        [9.9876e-01],
        [3.6584e-04],
        [9.9991e-01],
        [9.9998e-01],
        [2.7936e-05],
        [9.9168e-04],
        [9.9999e-01],
        [7.3645e-03],
        [9.9963e-01],
        [1.0000e+00],
        [1.1240e-03],
        [9.9644e-01],
        [9.0545e-01],
        [8.8640e-05],
        [7.0978e-02],
        [7.7036e-01],
        [1.0785e-03],
        [8.0095e-01],
        [7.6400e-04],
        [9.1136e-03],
        [5.7892e-01],
        [5.3183e-04],
        [1.2335e-01],
        [9.7619e-01],
        [9.9999e-01],
        [1.0000e+00],
        [1.3975e-02],
        [1.0594e-04],
        [7.1808e-02],
        [9.9989e-01],
        [9.9955e-01],
        [9.8544e-04],
        [9.9963e-01],
        [1.0000e+00],
        [5.3273e-03],
        [7.6510e-04],
        [4.5381e-04],
        [1.0000e+00],
        [5.7963e-05],
        [9.9976e-01],
        [9.9814e-01],
        [9.9799e-01],
        [1.4673e-01],
        [1.7237e-01],
        [6.6539e-02],
        [9.9626e-01],
        [1.4029e-03],
        [2.9983e-03],
        [9.9464e-01],
        [1.0000e+00],
        [9.7988e-01],
        [9.9934e-01],
        [1.2653e-01],
        [9.9220e-01],
        [3.1890e-03],
        [1.9879e-05],
        [1.9104e-02],
        [2.8301e-02],
        [1.6337e-02],
        [6.2726e-04],
        [1.6471e-04],
        [9.9999e-01],
        [1.0000e+00],
        [9.6908e-01],
        [1.0000e+00],
        [6.2917e-04],
        [1.8311e-01],
        [2.2778e-03],
        [2.1836e-01],
        [1.0000e+00],
        [4.1227e-01],
        [9.8061e-01],
        [2.2770e-04],
        [2.6435e-04],
        [7.4112e-04],
        [1.4680e-02],
        [3.5255e-02],
        [9.9528e-01],
        [9.9885e-01],
        [9.3013e-01],
        [1.1514e-04],
        [1.0049e-03],
        [9.3869e-01],
        [1.6075e-01],
        [3.1526e-04],
        [9.9999e-01],
        [9.5788e-01],
        [9.9979e-01],
        [9.9958e-01],
        [1.3337e-03],
        [3.1816e-02],
        [5.8224e-01],
        [9.9866e-01],
        [8.1658e-02],
        [1.5602e-02],
        [7.8745e-03],
        [1.0000e+00],
        [6.2599e-01],
        [1.0000e+00],
        [1.8297e-05],
        [1.6810e-04],
        [6.4818e-01],
        [8.5320e-05],
        [7.2607e-04],
        [1.9788e-04],
        [1.5423e-05],
        [1.0000e+00],
        [1.3107e-01],
        [8.9907e-02],
        [3.6049e-04],
        [1.8324e-02],
        [3.3323e-04],
        [7.3102e-03],
        [7.5085e-05],
        [8.3356e-04],
        [2.6897e-04],
        [1.0000e+00],
        [2.1863e-05],
        [3.1130e-05],
        [1.5388e-03],
        [3.8511e-02],
        [7.9602e-05],
        [2.7072e-03],
        [7.5952e-01],
        [5.7438e-01],
        [1.4323e-01],
        [1.0000e+00],
        [9.2790e-05],
        [1.4018e-03],
        [7.0754e-01],
        [9.9898e-01],
        [9.9999e-01],
        [2.8554e-02],
        [9.4971e-01],
        [9.9458e-01],
        [1.6395e-01],
        [9.9973e-01],
        [5.8377e-03],
        [1.4915e-07],
        [1.0511e-01],
        [2.8016e-04],
        [9.5086e-01],
        [8.9011e-03]], grad_fn=<SigmoidBackward0>)

# Evaluation

In [72]:
'''
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')
'''

# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9688

In [73]:

y_pred

tensor([[1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.]])