<a href="https://colab.research.google.com/github/harshs-data/Pytorch/blob/main/training_pipeline_using_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [37]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [38]:
df.shape

(569, 33)

In [39]:
df.drop(columns=['id', 'Unnamed: 32'], inplace = True)
df

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [40]:
df.shape

(569, 31)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   diagnosis                569 non-null    object
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  569 non-null    float64
 15  smoothness_se            569 non-null    float64
 16  compactness_se           569 non-null    float64
 17  concavity_se             569 non-null    float64
 18  concave points_se        569 non-null    float64
 19  symmetry_se              569 non-null    float64
 20  fractal_dimension_se     569 non-null    float64
 21  radius_worst             569 non-null    float64
 22  texture_worst            569 non-null    float64
 23  perimeter_worst          569 non-null    float64
 24  area_worst               569 non-null    float64
 25  smoothness_worst         569 non-null    float64
 26  compactness_worst        569 non-null    float64
 27  concavity_worst          569 non-null    float64
 28  concave points_worst     569 non-null    float64
 29  symmetry_worst           569 non-null    float64
 30  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), object(1)
memory usage: 137.9+ KB

In [42]:
df.describe()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [43]:
df.isnull().sum()

diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [44]:
df.duplicated().sum()

np.int64(0)

### Train test split

In [45]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2, random_state=42)

In [46]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((455, 30), (114, 30), (455,), (114,))

# scaling

In [47]:
scaler = StandardScaler()
df_train = scaler.fit_transform(X_train)
df_test = scaler.transform(X_test)

### LabelEncoder

In [48]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

### Numpy to pytorch tensors

In [70]:
X_train_tensor = torch.from_numpy(df_train.astype(np.float32))
X_test_tensor = torch.from_numpy(df_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [71]:
X_train_tensor.shape

torch.Size([455, 30])

### Defining the Model

In [132]:
class MysimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

  '''
  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss
    '''

Imp. parameters

In [133]:
learning_rate = 0.1
epochs = 25

In [134]:
# defining loss function
loss_function = nn.BCELoss()

### Training pipeline

In [135]:
# create model
model = MysimpleNN(X_train_tensor.shape[1])

In [136]:
# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

In [143]:
# define loop

for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1)) # Reshape y_train_tensor

  # zero gradients
  '''
  for param in model.parameters():
    if param.grad is not None:
        param.grad.zero_()
  '''
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  '''
  with torch.no_grad():
    for param in model.parameters():
      param -= learning_rate * param.grad
  '''
  optimizer.step()

  # print loss in each epoch

  print(f'Epoch: {epoch + 1}, loss: {loss.item()}')

Epoch: 1, loss: 0.16726095974445343
Epoch: 2, loss: 0.16487976908683777
Epoch: 3, loss: 0.1626279205083847
Epoch: 4, loss: 0.1604943871498108
Epoch: 5, loss: 0.15846934914588928
Epoch: 6, loss: 0.15654411911964417
Epoch: 7, loss: 0.15471090376377106
Epoch: 8, loss: 0.15296275913715363
Epoch: 9, loss: 0.15129339694976807
Epoch: 10, loss: 0.1496971696615219
Epoch: 11, loss: 0.14816899597644806
Epoch: 12, loss: 0.14670421183109283
Epoch: 13, loss: 0.14529868960380554
Epoch: 14, loss: 0.1439485251903534
Epoch: 15, loss: 0.14265026152133942
Epoch: 16, loss: 0.14140069484710693
Epoch: 17, loss: 0.14019685983657837
Epoch: 18, loss: 0.13903610408306122
Epoch: 19, loss: 0.1379159390926361
Epoch: 20, loss: 0.1368340402841568
Epoch: 21, loss: 0.13578835129737854
Epoch: 22, loss: 0.13477686047554016
Epoch: 23, loss: 0.1337977945804596
Epoch: 24, loss: 0.13284946978092194
Epoch: 25, loss: 0.13193029165267944

In [144]:
model.linear.weight

Parameter containing:
tensor([[ 0.4114,  0.3118,  0.1663,  0.3414,  0.1521,  0.2020,  0.1985,  0.4626,
          0.0290, -0.1215,  0.3061, -0.1690,  0.2011,  0.2818,  0.0235, -0.0620,
          0.0983, -0.0747, -0.0847, -0.1146,  0.2395,  0.4135,  0.2808,  0.4751,
          0.3053,  0.3051,  0.1182,  0.1599,  0.1447,  0.0678]],
       requires_grad=True)

In [145]:
model.linear.bias

Parameter containing:
tensor([-0.3031], requires_grad=True)

In [146]:
y_pred

tensor([[2.5278e-01],
        [9.9995e-01],
        [3.4523e-03],
        [1.1411e-01],
        [1.1328e-02],
        [9.8684e-01],
        [1.9831e-01],
        [2.5244e-02],
        [5.9303e-02],
        [9.8924e-01],
        [1.8502e-01],
        [9.9811e-01],
        [9.6166e-01],
        [2.3253e-02],
        [5.0374e-02],
        [9.9867e-01],
        [9.9970e-01],
        [9.9648e-01],
        [8.8827e-02],
        [2.6153e-02],
        [1.3708e-01],
        [9.2903e-01],
        [3.4070e-01],
        [4.2342e-02],
        [4.9153e-01],
        [8.8100e-01],
        [4.1777e-02],
        [9.9923e-01],
        [9.9435e-03],
        [8.5189e-03],
        [8.7204e-01],
        [4.4811e-02],
        [9.9338e-01],
        [9.9480e-01],
        [6.0873e-01],
        [3.4094e-02],
        [6.3871e-01],
        [1.3688e-02],
        [4.1376e-03],
        [1.4726e-01],
        [3.4812e-02],
        [1.0000e+00],
        [9.8769e-01],
        [4.7817e-03],
        [1.2338e-01],
        [5.6270e-03],
        [4.3648e-04],
        [2.7655e-02],
        [1.5137e-02],
        [7.0351e-02],
        [5.7749e-01],
        [4.2926e-02],
        [3.4649e-02],
        [3.0990e-01],
        [2.4896e-02],
        [9.0027e-01],
        [2.6497e-01],
        [5.4080e-02],
        [4.6636e-02],
        [4.6812e-01],
        [3.9515e-02],
        [1.7525e-01],
        [6.8719e-01],
        [2.6426e-01],
        [4.9837e-02],
        [1.7247e-01],
        [2.4495e-01],
        [9.1936e-02],
        [2.2816e-02],
        [8.2796e-01],
        [9.7902e-01],
        [8.3550e-01],
        [6.7030e-01],
        [1.6053e-01],
        [8.8100e-01],
        [5.8332e-02],
        [9.9761e-01],
        [8.1956e-02],
        [6.5717e-02],
        [8.7541e-03],
        [1.8885e-02],
        [7.4797e-01],
        [2.2066e-01],
        [7.9916e-03],
        [9.9714e-01],
        [1.2677e-02],
        [5.6841e-02],
        [4.0346e-02],
        [9.9945e-01],
        [6.0439e-02],
        [9.9899e-01],
        [9.9774e-01],
        [2.4433e-02],
        [3.9850e-02],
        [1.6698e-01],
        [6.4865e-01],
        [1.6979e-02],
        [6.4794e-03],
        [4.8242e-02],
        [4.1940e-03],
        [8.6171e-01],
        [2.8543e-02],
        [5.2902e-02],
        [4.3083e-03],
        [1.4886e-02],
        [5.6906e-03],
        [9.0066e-01],
        [2.3956e-01],
        [9.9890e-01],
        [9.9244e-01],
        [6.0306e-02],
        [3.1927e-02],
        [9.9984e-01],
        [6.4522e-02],
        [1.9454e-03],
        [1.0387e-01],
        [1.5549e-01],
        [2.1687e-01],
        [3.8988e-02],
        [5.5136e-02],
        [6.2472e-01],
        [9.2388e-01],
        [1.0000e+00],
        [2.3181e-02],
        [5.9527e-02],
        [9.9925e-01],
        [1.3811e-01],
        [5.1605e-02],
        [9.5516e-01],
        [4.9343e-02],
        [7.9637e-01],
        [6.2786e-03],
        [9.9595e-01],
        [6.5896e-02],
        [3.3895e-01],
        [2.8807e-02],
        [4.0196e-01],
        [7.6490e-01],
        [9.4729e-02],
        [1.0610e-02],
        [1.3644e-01],
        [9.7980e-01],
        [1.0749e-01],
        [9.8171e-01],
        [2.4348e-01],
        [9.6973e-01],
        [3.1841e-02],
        [8.8017e-01],
        [1.1331e-02],
        [3.4245e-01],
        [9.7844e-01],
        [2.0172e-01],
        [1.7578e-03],
        [4.2802e-02],
        [3.9368e-02],
        [8.6464e-01],
        [3.4008e-01],
        [2.8312e-02],
        [8.6259e-02],
        [9.9786e-01],
        [4.4262e-01],
        [4.4085e-02],
        [8.5914e-01],
        [1.3165e-01],
        [2.1508e-02],
        [9.9907e-01],
        [3.5640e-02],
        [1.6541e-02],
        [6.0192e-02],
        [6.1455e-02],
        [5.1983e-02],
        [2.7367e-01],
        [9.5741e-03],
        [8.0450e-01],
        [2.9936e-02],
        [1.0623e-01],
        [1.0165e-01],
        [5.5222e-01],
        [6.1771e-03],
        [9.8149e-01],
        [4.6389e-01],
        [1.1478e-01],
        [2.2178e-02],
        [7.8256e-01],
        [2.6940e-02],
        [8.8233e-01],
        [9.9814e-01],
        [5.4224e-03],
        [1.3465e-01],
        [9.4989e-01],
        [1.3962e-02],
        [9.3635e-01],
        [8.2588e-01],
        [4.5402e-02],
        [1.3599e-01],
        [5.1447e-02],
        [3.3067e-01],
        [3.5493e-01],
        [1.0118e-01],
        [1.3431e-03],
        [9.9208e-01],
        [6.7992e-02],
        [4.8075e-01],
        [1.2821e-01],
        [1.6915e-01],
        [1.5522e-01],
        [1.0000e+00],
        [1.5595e-01],
        [9.9997e-01],
        [2.3452e-02],
        [1.1046e-01],
        [9.9756e-01],
        [9.9698e-01],
        [1.0033e-02],
        [3.8261e-02],
        [9.8984e-01],
        [5.0001e-02],
        [9.9387e-01],
        [9.9999e-01],
        [1.2627e-02],
        [9.9993e-01],
        [9.9977e-01],
        [3.5188e-02],
        [3.4963e-01],
        [9.8724e-01],
        [9.9132e-01],
        [9.9973e-01],
        [2.0272e-01],
        [3.5282e-02],
        [5.9813e-02],
        [6.2314e-02],
        [9.2587e-01],
        [4.0158e-02],
        [9.6909e-01],
        [9.9961e-01],
        [9.9717e-01],
        [4.6991e-01],
        [6.4363e-03],
        [5.8702e-02],
        [4.4076e-01],
        [2.2512e-01],
        [9.4418e-02],
        [9.7508e-02],
        [2.5489e-02],
        [1.3024e-01],
        [9.8438e-01],
        [9.9478e-01],
        [4.7233e-01],
        [1.0154e-02],
        [9.9362e-01],
        [2.8201e-02],
        [4.7412e-02],
        [2.5269e-03],
        [5.4311e-02],
        [4.2564e-03],
        [9.9654e-01],
        [2.4803e-02],
        [1.7588e-01],
        [9.9929e-01],
        [9.5498e-01],
        [3.5833e-02],
        [7.3539e-01],
        [9.2412e-02],
        [9.9909e-01],
        [8.4100e-02],
        [1.3189e-01],
        [3.0428e-02],
        [2.3431e-02],
        [8.2048e-02],
        [8.9050e-02],
        [9.6408e-01],
        [8.8908e-03],
        [1.9595e-01],
        [9.2419e-01],
        [1.4747e-01],
        [1.4650e-02],
        [1.9251e-02],
        [9.9907e-02],
        [5.5415e-02],
        [2.6130e-01],
        [9.9853e-01],
        [2.9827e-01],
        [1.9975e-01],
        [6.5000e-01],
        [1.5522e-01],
        [9.2768e-01],
        [9.1521e-01],
        [9.7984e-01],
        [2.0400e-01],
        [8.7388e-01],
        [1.7765e-01],
        [6.9820e-03],
        [9.8859e-01],
        [9.6924e-01],
        [9.9443e-01],
        [3.5030e-02],
        [4.2919e-02],
        [8.6946e-02],
        [3.6192e-02],
        [2.5298e-01],
        [1.7123e-01],
        [6.2030e-02],
        [9.9506e-01],
        [3.9659e-02],
        [8.7452e-02],
        [2.9726e-01],
        [9.7353e-01],
        [1.4460e-02],
        [1.7415e-02],
        [9.0037e-01],
        [5.4713e-01],
        [1.0569e-02],
        [9.6937e-01],
        [1.7002e-02],
        [9.8566e-01],
        [9.9252e-01],
        [6.0168e-03],
        [4.6691e-02],
        [9.9457e-01],
        [1.1947e-01],
        [9.8075e-01],
        [9.9961e-01],
        [4.2977e-02],
        [9.6955e-01],
        [6.4054e-01],
        [1.2307e-02],
        [3.4670e-01],
        [7.7360e-01],
        [2.7275e-02],
        [4.7147e-01],
        [3.2170e-02],
        [9.1329e-02],
        [5.7198e-01],
        [2.5952e-02],
        [2.7588e-01],
        [8.1668e-01],
        [9.9530e-01],
        [9.9760e-01],
        [9.6684e-02],
        [1.0815e-02],
        [1.8504e-01],
        [9.7998e-01],
        [9.6489e-01],
        [3.7094e-02],
        [9.7844e-01],
        [9.9800e-01],
        [8.8358e-02],
        [3.7853e-02],
        [2.4545e-02],
        [9.9931e-01],
        [8.7731e-03],
        [9.8087e-01],
        [9.1945e-01],
        [9.7627e-01],
        [1.9867e-01],
        [5.0021e-01],
        [1.4718e-01],
        [9.4205e-01],
        [4.1358e-02],
        [5.2681e-02],
        [9.0628e-01],
        [9.9931e-01],
        [9.4916e-01],
        [9.8239e-01],
        [1.9880e-01],
        [9.4654e-01],
        [4.3564e-02],
        [4.5002e-03],
        [1.3195e-01],
        [8.4873e-02],
        [1.0102e-01],
        [2.1937e-02],
        [1.2453e-02],
        [9.9531e-01],
        [9.9998e-01],
        [7.6554e-01],
        [1.0000e+00],
        [2.7360e-02],
        [3.8358e-01],
        [3.8144e-02],
        [4.0904e-01],
        [1.0000e+00],
        [3.7718e-01],
        [8.8950e-01],
        [1.5880e-02],
        [1.3340e-02],
        [5.9839e-02],
        [1.0467e-01],
        [1.5925e-01],
        [9.2228e-01],
        [9.6076e-01],
        [7.6113e-01],
        [1.0071e-02],
        [2.6494e-02],
        [9.5891e-01],
        [3.5572e-01],
        [1.7367e-02],
        [9.9697e-01],
        [8.7855e-01],
        [9.7199e-01],
        [9.7170e-01],
        [4.7583e-02],
        [1.2459e-01],
        [5.2817e-01],
        [9.6357e-01],
        [2.4273e-01],
        [7.1425e-02],
        [5.7495e-02],
        [9.9872e-01],
        [5.6287e-01],
        [9.9997e-01],
        [6.2929e-03],
        [1.1263e-02],
        [5.5118e-01],
        [1.1070e-02],
        [2.7658e-02],
        [9.5879e-03],
        [6.2048e-03],
        [9.9986e-01],
        [3.8166e-01],
        [2.1066e-01],
        [9.1186e-02],
        [1.3127e-01],
        [2.3262e-02],
        [8.8611e-02],
        [1.8248e-02],
        [2.5067e-02],
        [4.0410e-02],
        [9.9917e-01],
        [5.2862e-03],
        [6.5479e-03],
        [2.8611e-02],
        [1.6624e-01],
        [7.9698e-03],
        [4.9839e-02],
        [4.6822e-01],
        [5.1357e-01],
        [2.8317e-01],
        [9.9446e-01],
        [1.0058e-02],
        [5.1422e-02],
        [5.5935e-01],
        [9.7591e-01],
        [9.9242e-01],
        [1.1590e-01],
        [8.2532e-01],
        [8.6388e-01],
        [3.4533e-01],
        [9.7322e-01],
        [1.1287e-01],
        [4.6579e-03],
        [2.1857e-01],
        [1.4854e-02],
        [7.6820e-01],
        [4.7382e-02]], grad_fn=<SigmoidBackward0>)

# Evaluation

In [147]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5323176383972168

In [148]:
y_pred

tensor([[0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.]])